language: python
matrix:
   include:
     # We don't actually use the Travis Python, but this keeps it organized.
     - python: "2.7"
       env: 
          - ENV_FILE=environment_py27.yml
          - ENV_NAME=img_pipe_py2
     - python: "3.6"
       env: 
          - ENV_FILE=environment_py36.yml
          - ENV_NAME=img_pipe_py3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
cache: bundler
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # These dont matter, but should be set
  - export FREESURFER_HOME="$HOME"
  - export SUBJECTS_DIR="$HOME"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda env create -f $ENV_FILE
  - source activate $ENV_NAME

script:
  # Your test script goes here
  - pwd
  - cd tests
  - python tests.py
